import Foundation

enum MarkdownRenderer {
  static func render(_ meeting: MeetingDocument) -> String { renderLive(meeting) }

  static func renderLive(_ meeting: MeetingDocument) -> String {
    frontmatter(meeting, artifact: "live-transcript")
      + "\n# \(meeting.title) — Live transcript\n\n"
      + "> This is provisional live ASR and may change after final transcription.\n\n"
      + renderTurns(meeting.transcript)
  }

  static func renderTranscript(_ meeting: MeetingDocument) -> String {
    var output = frontmatter(meeting, artifact: "final-transcript")
    output += "\n# \(meeting.title) — Transcript\n\n"
    let turns = meeting.transcript.sorted { $0.start < $1.start }
    if let topics = meeting.insights?.topics, !topics.isEmpty {
      for topic in topics.sorted(by: { $0.start < $1.start }) {
        output +=
          "## \(topic.title) [\(topic.start.meetingTimestamp)–\(topic.end.meetingTimestamp)]\n\n"
        output += renderTurns(turns.filter { $0.end >= topic.start && $0.start <= topic.end })
      }
    } else {
      output += renderSegmentedTurns(turns)
    }
    return output
  }

  static func renderMeeting(_ meeting: MeetingDocument) -> String {
    var output = frontmatter(meeting, artifact: "meeting-memory")
    let transcriptAvailable = meeting.transcriptDeletedAt == nil
    output += "\n# \(meeting.title)\n\n"
    if let calendar = meeting.calendar {
      output += "## Participants\n\n"
      let participants = uniqueParticipants(calendar)
      output +=
        participants.isEmpty
        ? "_No calendar participants available._\n\n"
        : participants.map { "- \($0.name)\($0.email.map { " <\($0)>" } ?? "")" }.joined(
          separator: "\n") + "\n\n"
    }
    guard let insights = meeting.insights else {
      if transcriptAvailable {
        output +=
          "## Summary\n\n_No structured summary was generated. Search `transcript.md` for complete evidence._\n\n"
        output += "## Transcript\n\n[Open the complete timestamped transcript](transcript.md)\n"
      } else {
        output += "## Summary\n\n_No structured summary was generated._\n\n"
        output += "## Transcript\n\n_Deleted according to the retention policy._\n"
      }
      return output
    }
    output += "## Summary\n\n\(insights.summary)\n\n"
    output += "## Topics\n\n"
    output +=
      insights.topics.map {
        "- **\($0.title)** [\($0.start.meetingTimestamp)–\($0.end.meetingTimestamp)]: \($0.summary)"
      }.joined(separator: "\n") + "\n\n"
    output += renderEvidence("Decisions", insights.decisions, linkToTranscript: transcriptAvailable)
    output += renderEvidence("Action items", insights.actionItems, linkToTranscript: transcriptAvailable)
    output += renderEvidence("Open questions", insights.openQuestions, linkToTranscript: transcriptAvailable)
    output += renderEvidence("Key statements", insights.keyStatements, linkToTranscript: transcriptAvailable)
    output += "## Provenance\n\n- Generated by: \(insights.generator)\n"
    output += "- Generated at: \(insights.generatedAt.ISO8601Format())\n"
    if transcriptAvailable {
      output += "- Every derived item should be verified against [the transcript](transcript.md).\n"
    } else if let deletedAt = meeting.transcriptDeletedAt {
      output += "- The word-for-word transcript was deleted by the retention policy at \(deletedAt.ISO8601Format()).\n"
    }
    return output
  }

  private static func frontmatter(_ meeting: MeetingDocument, artifact: String) -> String {
    var output = """
      ---
      id: \(meeting.id.uuidString)
      title: \(yaml(meeting.title))
      artifact: \(artifact)
      started_at: \(meeting.startedAt.ISO8601Format())
      status: \(meeting.status.rawValue)
      transcription_version: \(meeting.transcriptionVersion)
      """
    if let endedAt = meeting.endedAt { output += "\nended_at: \(endedAt.ISO8601Format())" }
    if let deletedAt = meeting.transcriptDeletedAt {
      output += "\ntranscript_deleted_at: \(deletedAt.ISO8601Format())"
    }
    if let calendar = meeting.calendar {
      output += "\ncalendar_event_id: \(yaml(calendar.eventIdentifier))"
      output += "\ncalendar: \(yaml(calendar.calendarTitle))"
      output += "\nscheduled_start: \(calendar.scheduledStart.ISO8601Format())"
      output += "\nscheduled_end: \(calendar.scheduledEnd.ISO8601Format())"
      if let location = calendar.location { output += "\nlocation: \(yaml(location))" }
    }
    return output + "\n---\n"
  }

  private static func renderTurns(_ turns: [TranscriptTurn]) -> String {
    turns.sorted(by: { $0.start < $1.start }).map {
      "**[\($0.start.meetingTimestamp)] \($0.speaker):** \($0.text.trimmingCharacters(in: .whitespacesAndNewlines))\n"
    }.joined(separator: "\n")
  }

  private static func renderSegmentedTurns(_ turns: [TranscriptTurn]) -> String {
    var output = ""
    var bucket = -1
    for turn in turns {
      let nextBucket = Int(turn.start / 480)
      if nextBucket != bucket {
        bucket = nextBucket
        output += "## Segment \(bucket + 1) [\(TimeInterval(bucket * 480).meetingTimestamp)]\n\n"
      }
      output +=
        "**[\(turn.start.meetingTimestamp)] \(turn.speaker):** \(turn.text.trimmingCharacters(in: .whitespacesAndNewlines))\n\n"
    }
    return output
  }

  private static func renderEvidence(
    _ heading: String,
    _ items: [EvidenceItem],
    linkToTranscript: Bool
  ) -> String {
    var output = "## \(heading)\n\n"
    output +=
      items.isEmpty
      ? "_None identified._\n\n"
      : items.map {
        let timestamp = linkToTranscript
          ? "[\($0.timestamp.meetingTimestamp)](transcript.md)"
          : $0.timestamp.meetingTimestamp
        return "- \($0.text)\($0.owner.map { " — **\($0)**" } ?? "") \(timestamp)"
      }.joined(separator: "\n") + "\n\n"
    return output
  }

  private static func uniqueParticipants(_ calendar: CalendarMetadata) -> [MeetingParticipant] {
    var seen = Set<String>()
    return ([calendar.organizer].compactMap { $0 } + calendar.participants).filter {
      let key = ($0.email ?? $0.name).lowercased()
      return seen.insert(key).inserted
    }
  }

  private static func yaml(_ value: String) -> String {
    "\"\(value.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\""))\""
  }
}
